### ISSUE TITLE
www.gov.uk fails to parse properly

### ISSUE THREAD

**Issue by ArmyDev** [remusao/tldts#1592]

**Comment by remusao** [comment]
Hi @ArmyDev,

I believe the parsing is correct, `gov.uk` is a [valid suffix](https://github.com/publicsuffix/list/blob/0db734249949ba0f1f3d934bf9b97c47f5d1c05e/public_suffix_list.dat#L6485) according to https://github.com/publicsuffix/list. I agree that it looks a bit weird since `https://www.gov.uk` is a website, but I think it's correct.

I hope that helps,

**Comment by ArmyDev** [comment]
In my system I require to use the _domainWithoutSuffix_ and the _subdomain_ properties, given the www.gov.uk url it resolves to `www` for  _domainWithoutSuffix_ and to nothing for the the _subdomain_. I also believe this would fail for most of the gov websites. Should I parse them separately?

**Comment by remusao** [comment]
You might need to handle this separately because from what I can see the behavior is correct, the public suffix here is `gov.uk`, hence the domain without suffix should be `www`, although that seems counter-intuitive. It is the result of using the public suffix list for the parsing.

**Comment by ArmyDev** [comment]
Ok, thanks
