### ISSUE TITLE
[tldts-experimental] `isIcann` field error

### ISSUE THREAD

**Issue by SukkaW** [remusao/tldts#2121]
```js
const tldtsExperimental = require("tldts-experimental")
const tldts = require("tldts")
console.log(tldtsExperimental.parse('mine.torrent.pw'))
console.log(tldts.parse('mine.torrent.pw'))
```

https://runkit.com/sukkaw/66af9605197c730008ca4ef7

`tldtsExperimental.parse('mine.torrent.pw')` returns `{ isIcann: false }` while `tldts.parse('mine.torrent.pw')` returns `{ isIcann: true }`.

**Comment by remusao** [comment]
Hi @SukkaW, thanks for reaching out! I will need to check why that flag is not set properly. I think there was something related to some optimization not keeping track of the flag, but since it's possible to disable/enabled the Private section at runtime I think it should be possible to know where a given rule was from.

**Comment by remusao** [comment]
Hi again @SukkaW, I now remember about this limitation. In order to reduce the size of the data further and optimize the matching, the experimental mode ignores all single-labels from the public suffix list. The reason is that returning the last label of the hostname as public suffix is the default behavior if not rule was found, so this does not make a difference in practice (e.g. if `pw` is part of the public suffix list, it is not stored as part of the data, because we know that if no other more specific suffix matches, we will default to `pw` anyway). The consequence of this choice is that, we don't know if `pw` was from the ICANN or PRIVATE section of the list. If your use-case relies on knowing this information precisely, you should likely use `tldts` instead of `tldts-experimental`.

**Comment by remusao** [comment]
I am closing this issue since there is no plan on changing the behavior of `tldts-experimental` and people are encouraged to use the normal `tldts` package whenever the behavior outlined above is important to their use-case.
