### ISSUE TITLE
Not correctly parsing public suffix for blogspot.com

### ISSUE THREAD

**Issue by davidbielik** [remusao/tldts#511]
The `tldjs` package correctly parsed "subdomain.blogspot.com" as having a public suffix of "blogspot.com".

This `tldts` package seems to not recognize `blogspot.com` as a public suffix, as noted in the [Public Suffix List](https://publicsuffix.org/list/public_suffix_list.dat).

Steps to reproduce:

```
const tldjs = require("tldjs");
const tldts = require("tldts");
const input = "subdomain.blogspot.com";
if (tldjs.getPublicSuffix(input) !== tldts.getPublicSuffix(input)) {
  throw new Error(`${input} did not match in both libraries`);
}
```
![image](https://user-images.githubusercontent.com/7410770/78741424-4c5bee00-7927-11ea-8731-b307aa3b0d22.png)

**Comment by remusao** [comment]
Hi @davidbielik and thank you for taking the time to open an issue,

This one is a bit tricky and is the expected behavior (although that might seem counter-intuitive). Let me try to explain. There are two sections in the public suffix list: ICANN domains and private domains. In `tldjs` both sections will be looked-up by default. At the time we found that this behavior was surprising to a lot of users of the library because it contains suffixes like `blogspot.com` or `us-east-1.amazonaws.com` which means that the domain of `myapp.us-east-1.amazonaws.com` is actually `myapp.us-east-1.amazonaws.com` whereas a lot of people would have expected `amazonaws.com`.

Long story short, depending on your use-case you might want to lookup the private section of the list or not and in `tldts` the default is to not do it (which is somewhat an opinionated choice). You can enable it using an option:

```js
const { parse } = require('tldts');
parse('subdomain.blogspot.com', { allowPrivateDomains: true });
// {
//   domain: 'subdomain.blogspot.com',
//   domainWithoutSuffix: 'subdomain',
//   hostname: 'subdomain.blogspot.com',
//   isIcann: false,
//   isIp: false,
//   isPrivate: true,
//   publicSuffix: 'blogspot.com',
//   subdomain: ''
// }
```

There are a few other options that one can use to customize the behavior of `tldts` which you can find documented here: https://github.com/remusao/tldts/tree/master/packages/tldts#api

I hope this helps,
Best,

**Comment by davidbielik** [comment]
Very helpful, thanks for clarifying!
